### ISSUE TITLE
Is it okay to run producer and consumer in the same machine ?

### ISSUE THREAD

**Issue by fsck-mount** [LivePersonInc/kafka-java-bridge#17]
As both of them needs java instance running at the same port, is it okay to run both of them in the same machine ?

**Comment by 1ManSmoking** [comment]
Yes, they work perfectly together.
Producer doesn't need any loopback port and they both run under the same
jvm instance.

On Jun 25, 2017 22:57, "Gowtham Sai" <notifications@github.com> wrote:

As both of them needs java instance running at the same port, is it okay to
run both of them in the same machine ?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/LivePersonInc/kafka-java-bridge/issues/17>, or mute the
thread

**Comment by fsck-mount** [comment]
I've a problem that I don't understand why it's happening. Suddenly producing messages to kafka stopped. At the same time, logging to newrelic is also stopped. And restart your application, everything is fine. 

After sometime, again same problem. Couldn't able to find out the issue. Any help?


Here is my producer code, you see any issue with this?

```node
var StringProducer = require('kafka-java-bridge').StringProducer;
var BinaryProducer = require('kafka-java-bridge').BinaryProducer;

var zkUrl = process.env.ZK_URL || 'localhost:2181';

var stringProducer = new StringProducer( { zookeeperUrl: zkUrl } );
var binaryProducer = new BinaryProducer( { zookeeperUrl: zkUrl } );

exports.send = function (topic, messages) {

        if (!(messages.constructor == Array)) messages = [messages];
        messages.forEach(function (msg) {
                if (msg.constructor == String) stringProducer.send(topic, msg);
                else if (msg.constructor == Buffer) binaryProducer.send(topic, msg);
                else if (msg.constructor == Object) stringProducer.send(topic, JSON.stringify(msg));
                else throw "Invalid Message Type!"
        });
}

process.on('SIGINT', function() {
    stringProducer.close(function(err){
        binaryProducer.close(function(err) {
            process.exit();
        });
    });
});
```

**Comment by 1ManSmoking** [comment]
No idea.
Nothing we ever saw in relatiin to kafka-java-bridge.
How does newrelic work?
Does it send data over the the network?
If so perhaps try to disable it and see what happens.
Is it a network issue?
Isolate the lroblem.


On Jun 25, 2017 23:07, "Gowtham Sai" <notifications@github.com> wrote:

I've a problem that I don't understand why it's happening. Suddenly
producing messages to kafka stopped. At the same time, logging to newrelic
is also stopped. And restart your application, everything is fine.

After sometime, again same problem. Couldn't able to find out the issue.
Any help?

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/LivePersonInc/kafka-java-bridge/issues/17#issuecomment-310925013>,
or mute the thread

**Comment by fsck-mount** [comment]
Yes, Newrelic works over network. It's an APM. But, the kafka connection is private, it don't need network to work. 

Does producer ever produces error messages? If so, what's the event? How can I re-start the producer... ?

**Comment by 1ManSmoking** [comment]
You get producer errors by send method callback.
You don't restart the producer.
Close it and create a new one.


On Jun 26, 2017 15:02, "Gowtham Sai" <notifications@github.com> wrote:

Yes, Newrelic works over network. It's an APM. But, the kafka connection is
private, it don't need network to work.

Does producer ever produces error messages? If so, what's the event? How
can I re-start the producer... ?

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/LivePersonInc/kafka-java-bridge/issues/17#issuecomment-311039758>,
or mute the thread

**Comment by fsck-mount** [comment]
I was not caring about call back. I'll try to catch error in call back and lets' see, if I get any interesting stuff there.

**Comment by fsck-mount** [comment]
Hey @1ManSmoking , 

Can you please review the code. I'm not that expert in this area. Can you just check it once and lemme know if I'm doing anything wrong here. 

```node
var StringProducer = require('kafka-java-bridge').StringProducer;
var BinaryProducer = require('kafka-java-bridge').BinaryProducer;

var zkUrl = process.env.ZK_URL;

var stringProducer = new StringProducer( { zookeeperUrl: zkUrl } );
var binaryProducer = new BinaryProducer( { zookeeperUrl: zkUrl } );

module.exports = function (nr) {
	return { 
		send: nr.createTracer('kafka', function (topic, messages) {

			if (messages.constructor != Array) messages = [messages];
			
			messages.forEach(function (msg) {
				if (msg.constructor == String) stringProducer.send(topic, msg, function (err, msgMetadata) {
					if (err) {
						nr.noticeError(err, [gs]);
						setTimeout(function () {
							stringProducer.close(function (err) { if (err) nr.noticeError(err); });
						}, 300);
					}
					stringProducer = new StringProducer( { zookeeperUrl: zkUrl } );
					this.send(topic, messages);
				});
				else if (msg.constructor == Buffer) binaryProducer.send(topic, msg, function (err, msgMetadata) {
					if (err) {
						nr.noticeError(err, [gs]);
						setTimeout(function () {
							binaryProducer.close(function (err) { if (err) nr.noticeError(err); });
						}, 300);
					}
					binaryProducer = new BinaryProducer( { zookeeperUrl: zkUrl } );
					this.send(topic, messages);
				});
				else if (msg.constructor == Object) stringProducer.send(topic, JSON.stringify(msg), function (err, msgMetadata) {
					if (err) {
						nr.noticeError(err, [gs]);
						setTimeout(function () {
							stringProducer.close(function (err) { if (err) nr.noticeError(err); });
						}, 300);
					}
					stringProducer = new StringProducer( { zookeeperUrl: zkUrl } );
					this.send(topic, messages);
				});
				else throw "Invalid Message Type!"
			});
			nr.endTransaction();
		}),

		close: function () {

			setTimeout(function () {
				stringProducer.close(function (err) { if (err) nr.noticeError(err) });
				binaryProducer.close(function (err) { if (err) nr.noticeError(err) });
			}, 300);

		}
	}
}

process.on('SIGINT', function() {
	stringProducer.close(function (err) { if (err) nr.noticeError(err); });
	binaryProducer.close(function (err) { if (err) nr.noticeError(err); });
	setTimeout(function () {
		process.exit();
	}, 300);
});

```

**Comment by 1ManSmoking** [comment]
Already OOO today.
Will take a look tomorrow.

**Comment by fsck-mount** [comment]
@1ManSmoking , 

Sure, no problem. Thanks :)

Don't mind., the only thing is, events are very important. Can't afford to loose even a single event. 
Hope you understand. 
I really appreciate your effort.

**Comment by 1ManSmoking** [comment]
Why the timeout before close producer?
It is in the example only to allow logs to print before shutdown.
No need to put it in the code.
After the close, not sure "this" is what you want it to be.
As previously suggested, try to disable nr and print errors to log/console.
Try this and see what happens.
In addition, see how many time nr.createTracer is called, it depends on how you use the module.

**Comment by fsck-mount** [comment]
Thank you so much your effort. 

1. I used set timeout, just in case, producer closing is taking too much time which generally won't. Sure, will remove this. 

2. I used `this.send` as sending message was failed, I want to resend it again. That's why (I assumed this.send will refer to module.exports.send. ) There must be a better way of doing. 

3. Sure will disable and will try to print the logs. 

4. nr.createTracer is suppose to measure how much time we are spending in this loop. It will be called once whenever I call producer.send.

**Comment by fsck-mount** [comment]
Hey @1ManSmoking , Can I run 2 consumers in the same machine (with same server port?) ?

There is situation, where I need to consume from 2 different files in the same machine. Will that be okay, if I pass the same serverPort ?

Imagine this as data pipeline. 
One JS (processor.js which imports consumer) processes the events and then send it back to kafka, 
another one (syncer.js same machine) consumes from that topic send it destination source. 

Can we have them both on the same server port ?

**Comment by 1ManSmoking** [comment]
No, that wont work.
You can either specify different ports or consume the messages using a
single consumer and then pass them to two different handlers.

**Comment by fsck-mount** [comment]
@1ManSmoking , 

Yea, using different ports now., Okay, I'll close this issue as we are deviating from the actual topic and others might feel confusing. 

Q: Is it okay to run producer and consumer in the same machine ?
A: yes, you can have. 

Q: Is it okay to run 2 consumers initialised in the same machine ?
A. Yes, you can with different ports. No, you can't do with same port. 


Thanks @1ManSmoking.
