### ISSUE TITLE
Too many rebalance error

### ISSUE THREAD

**Issue by ersumitchh** [LivePersonInc/kafka-java-bridge#5]
Receiving too many rebalance error for a particular topic.

error Error: Error running instance method\nkafka.common.ConsumerRebalanceFailedException: topic-1466169990968-706600d6 can't rebalance after 10 retries\n\tat kafka.consumer.ZookeeperConsumerConnector$ZKRebalancerListener.syncedRebalance(ZookeeperConsumerConnector.scala:633)\n\tat kafka.consumer.ZookeeperConsumerConnector.kafka$consumer$ZookeeperConsumerConnector$$reinitializeConsumer(ZookeeperConsumerConnector.scala:905)\n\tat kafka.consumer.ZookeeperConsumerConnector.consume(ZookeeperConsumerConnector.scala:240)\n\tat kafka.javaapi.consumer.ZookeeperConsumerConnector.createMessageStreams(ZookeeperConsumerConnector.scala:85)\n\tat kafka.javaapi.consumer.ZookeeperConsumerConnector.createMessageStreams(ZookeeperConsumerConnector.scala:97)\n\tat com.liveperson.kafka.consumer.MultiThreadHLConsumer.start(MultiThreadHLConsumer.java:55)\n\tat sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\n\tat sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)\n\tat sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\n\tat java.lang.reflect.Method.invoke(Method.java:498)\n\n    at Error (native)

**Comment by 1ManSmoking** [comment]
This error is coming from confluent's kafka client.
It is mentioned in their [wiki page](https://cwiki.apache.org/confluence/display/KAFKA/FAQ#FAQ-Myconsumerseemstohavestopped,why?):

consumer rebalancing fails (you will see ConsumerRebalanceFailedException): This is due to conflicts when two consumers are trying to own the same topic partition. The log will show you what caused the conflict (search for "conflict in ").
If your consumer subscribes to many topics and your ZK server is busy, this could be caused by consumers not having enough time to see a consistent view of all consumers in the same group. If this is the case, try Increasing rebalance.max.retries and rebalance.backoff.ms.
**Another reason could be that one of the consumers is hard killed**. Other consumers during rebalancing won't realize that consumer is gone after zookeeper.session.timeout.ms time. In the case, **make sure that rebalance.max.retries \* rebalance.backoff.ms > zookeeper.session.timeout.ms**.

**Comment by ersumitchh** [comment]
Well, I tried increasing rebalance.max.retries but still getting these errors. After increasing rebalance.backoff.ms i'm receiving very less rebalance error.
Thanks for the explanation.
